name: JsonValidate
description: Validates a json file against a schema using ajv
author: Zingabopp
inputs:
  json-schema:
    description: Path to the json schema file
    required: true
  json-file:
    description: Path to the json file to validate
    required: true
  use-draft:
    description: Specify which schema the json-schema uses. Draft-07 is default, draft-04 and draft-06 are supported.
    required: false
  allow-online-fetch:
    description: Allow the schema specified in the json-file to be downloaded.
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
